结合[菜鸟教程](https://www.runoob.com/numpy/numpy-tutorial.html)和自己敲的实例进行学习，我只学了我需要用到的部分，如搭建我在炒股要用的股票分析项目需要pandas，但pandas需要Numpy。。。其他强大功能忽略，等用到的时候再说。下面是看的时候想到的问题和一些例子。

## [ndarray的数据类型](https://www.runoob.com/numpy/numpy-dtype.html)

问：为什么[ndarray的数据类型](https://www.runoob.com/numpy/numpy-dtype.html)会有那么多？对比Python语法仅支持整数、浮点数和复数3种类型。

答：
- 科学计算涉及数据较多，对存储和性能都有较高要求。
- 对元素类型精细定义，有助于NumPy合理使用存储空间井优化性能。
- 对元素类型精细定义，有助于程序员对程序规模有合理评估。

In [12]:
a = np.array([[0,1,2,3,4],[9,8,7,6]]) #非同质对象
a.shape

<ipython-input-12-b688e1aba478>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a = np.array([[0,1,2,3,4],[9,8,7,6]])


(2,)

In [13]:
a.dtype #这里显示类型为‘o’，即object

dtype('O')

In [14]:
a #尽量避免这样使用

array([list([0, 1, 2, 3, 4]), list([9, 8, 7, 6])], dtype=object)

## ndarray数组创建

除了[菜鸟上](https://www.runoob.com/numpy/numpy-array-creation.html) 相关实例，这里补充一点

In [16]:
x = np.ones((2,3,4))
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [17]:
x.shape

(2, 3, 4)

这里(2,3,4)表示的含义是，从外到内，最大的中括号有2个，其中每个里又有3个中括号，再其中又有4个元素（也就是4个1），所以认为是数组的最外层到最内层逐渐变化的数据维度的表示方式

In [27]:
b = np.linspace(1,10,10,endpoint=False)

In [28]:
b

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])